# Generated by Django 5.2.1 on 2025-08-24 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_insumo_activo_insumo_fecha_creacion'),
        ('ventas', '0002_venta_folio_ticket_venta_uniq_pizzeria_folio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('factor_rendimiento_esperado', models.FloatField(default=1.0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('insumo_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='inventario.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('unidad', models.CharField(max_length=20)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.insumo')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='inventario.formulainsumo')),
            ],
        ),
        migrations.CreateModel(
            name='LoteProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_objetivo', models.FloatField()),
                ('unidad_objetivo', models.CharField(max_length=20)),
                ('rendimiento_real', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('confirmado', models.BooleanField(default=False)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='inventario.formulainsumo')),
                ('pizzeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.pizzeria')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
