# Generated by Django 5.2.1 on 2025-08-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_formulainsumo_formulaingrediente_loteproduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteproduccion',
            name='unidad_objetivo',
            field=models.CharField(choices=[('pieza', 'Pieza'), ('gramo', 'Gramo'), ('kilogramo', 'Kilogramo'), ('litro', 'Litro'), ('mililitro', 'Mililitro')], max_length=20),
        ),
    ]
