# Generated by Django 5.2.1 on 2025-08-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzerias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzeria',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='id_local',
            field=models.IntegerField(default=999, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='zona',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
