# Generated by Django 5.2.1 on 2025-09-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzerias', '0002_pizzeria_email_pizzeria_hora_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzeria',
            name='id_local',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
