# Generated by Django 5.2.1 on 2025-06-03 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pizzería',
                'verbose_name_plural': 'Pizzerías',
                'db_table': 'pizzería',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dueno', models.ForeignKey(db_column='dueño_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL)),
                ('pizzeria', models.ForeignKey(db_column='pizzería_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.pizzeria')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DuenoPizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dueno', models.ForeignKey(db_column='dueño_id', on_delete=django.db.models.deletion.CASCADE, related_name='pizzeria_asignaciones', to=settings.AUTH_USER_MODEL)),
                ('pizzeria', models.ForeignKey(db_column='pizzería_id', on_delete=django.db.models.deletion.CASCADE, related_name='dueño_asignaciones', to='ventas.pizzeria')),
            ],
            options={
                'verbose_name': 'Asignación Dueño-Pizzería',
                'verbose_name_plural': 'Asignaciones Dueño-Pizzería',
                'db_table': 'dueño_pizzería',
                'unique_together': {('dueno', 'pizzeria')},
            },
        ),
    ]
