# Generated by Django 5.2.1 on 2025-08-10 00:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pizzería',
                'verbose_name_plural': 'Pizzerías',
                'db_table': 'pizzeria',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('canal', models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('LLEVAR', 'Llevar'), ('MOSTRADOR', 'Mostrador'), ('PLATAFORMAS', 'Plataformas'), ('DELIVERY', 'Delivery')], default='MOSTRADOR', max_length=50)),
                ('metodo_pago', models.CharField(default='EFECTIVO', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dueno', models.ForeignKey(db_column='dueno_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL)),
                ('pizzeria', models.ForeignKey(db_column='pizzeria_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.pizzeria')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Item de Venta',
                'verbose_name_plural': 'Items de Venta',
                'db_table': 'venta_producto',
            },
        ),
        migrations.CreateModel(
            name='VentaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('toma_pedido_inicio', 'Inicio toma de pedido'), ('toma_pedido_fin', 'Fin toma de pedido'), ('preparacion_inicio', 'Inicio preparación'), ('preparacion_fin', 'Fin preparación'), ('envio_inicio', 'Inicio envío'), ('envio_fin', 'Fin envío'), ('regreso_repartidor', 'Regreso repartidor'), ('pago', 'Pago realizado'), ('cancelada', 'Venta cancelada')], max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='ventas.venta')),
            ],
            options={
                'db_table': 'venta_etapa',
                'ordering': ['timestamp'],
                'unique_together': {('venta', 'etapa')},
            },
        ),
    ]
