# Generated by Django 5.2.1 on 2025-08-11 16:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='folio_ticket',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='venta',
            constraint=models.UniqueConstraint(condition=models.Q(('folio_ticket__isnull', False), models.Q(('folio_ticket', ''), _negated=True)), fields=('pizzeria', 'folio_ticket'), name='uniq_pizzeria_folio'),
        ),
    ]
