# Generated by Django 5.2.1 on 2025-06-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_producto_venta_canal_ventaproducto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ventaproducto',
            unique_together=set(),
        ),
    ]
