# Generated by Django 5.2.1 on 2025-06-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_ventaproducto_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, help_text='¿Está disponible para la venta?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(default='General1', help_text='Categoría del producto (ej. Pizza, Bebida, Postre)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del producto (opcional)', null=True),
        ),
    ]
