# Generated by Django 5.2.1 on 2025-06-15 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_producto_activo_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pizzeria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ventas.pizzeria'),
            preserve_default=False,
        ),
    ]
