# Generated by Django 5.2.1 on 2025-06-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_producto_pizzeria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='canal',
            field=models.CharField(default='MOSTRADOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(default='EFECTIVO', max_length=50),
        ),
    ]
