# Generated by Django 5.2.1 on 2025-06-16 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_venta_canal_alter_venta_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.producto'),
        ),
    ]
