# Generated by Django 5.2.1 on 2025-06-30 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_alter_venta_fecha'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='duenopizzeria',
            name='dueno',
            field=models.ForeignKey(db_column='dueno_id', on_delete=django.db.models.deletion.CASCADE, related_name='pizzeria_asignaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='duenopizzeria',
            name='pizzeria',
            field=models.ForeignKey(db_column='pizzeria_id', on_delete=django.db.models.deletion.CASCADE, related_name='dueno_asignaciones', to='ventas.pizzeria'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='canal',
            field=models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('LLEVAR', 'Llevar'), ('MOSTRADOR', 'Mostrador'), ('PLATAFORMAS', 'Plataformas')], default='MOSTRADOR', max_length=50),
        ),
        migrations.AlterField(
            model_name='venta',
            name='dueno',
            field=models.ForeignKey(db_column='dueno_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='pizzeria',
            field=models.ForeignKey(db_column='pizzeria_id', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='ventas.pizzeria'),
        ),
        migrations.AlterModelTable(
            name='duenopizzeria',
            table='dueno_pizzeria',
        ),
        migrations.AlterModelTable(
            name='pizzeria',
            table='pizzeria',
        ),
    ]
