# Generated by Django 5.2.1 on 2025-06-30 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_alter_duenopizzeria_dueno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('toma_pedido_inicio', 'Inicio toma de pedido'), ('toma_pedido_fin', 'Fin toma de pedido'), ('preparacion_inicio', 'Inicio preparación'), ('preparacion_fin', 'Fin preparación'), ('envio_inicio', 'Inicio envío'), ('envio_fin', 'Fin envío'), ('regreso_repartidor', 'Regreso repartidor'), ('pago', 'Pago realizado')], max_length=30)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='ventas.venta')),
            ],
            options={
                'db_table': 'venta_etapa',
                'ordering': ['timestamp'],
                'unique_together': {('venta', 'etapa')},
            },
        ),
    ]
