# Generated by Django 5.2.1 on 2025-07-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_ventaetapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaetapa',
            name='etapa',
            field=models.CharField(choices=[('toma_pedido_inicio', 'Inicio toma de pedido'), ('toma_pedido_fin', 'Fin toma de pedido'), ('preparacion_inicio', 'Inicio preparación'), ('preparacion_fin', 'Fin preparación'), ('envio_inicio', 'Inicio envío'), ('envio_fin', 'Fin envío'), ('regreso_repartidor', 'Regreso repartidor'), ('pago', 'Pago realizado'), ('cancelada', 'Venta cancelada')], max_length=30),
        ),
    ]
