# Generated by Django 5.2.1 on 2025-07-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_alter_ventaetapa_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='canal',
            field=models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('LLEVAR', 'Llevar'), ('MOSTRADOR', 'Mostrador'), ('PLATAFORMAS', 'Plataformas'), ('DELIVERY', 'Delivery')], default='MOSTRADOR', max_length=50),
        ),
    ]
