# Generated by Django 5.2.1 on 2025-07-19 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('subgerente', 'Subgerente'), ('empleado', 'Empleado'), ('dueno', 'Dueño'), ('cajero', 'Cajero'), ('solo_lectura', 'Solo lectura')], default='empleado', max_length=30),
        ),
        migrations.CreateModel(
            name='UsuarioPizzeriaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('dueno', 'Dueño'), ('gerente', 'Gerente'), ('subgerente', 'Subgerente'), ('cajero', 'Cajero'), ('empleado', 'Empleado')], max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pizzeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_con_rol', to='ventas.pizzeria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_por_pizzeria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de usuario en pizzería',
                'verbose_name_plural': 'Roles de usuarios en pizzerías',
                'db_table': 'usuario_pizzeria_rol',
                'unique_together': {('user', 'pizzeria')},
            },
        ),
    ]
