# Generated by Django 5.2.1 on 2025-07-21 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_alter_userprofile_rol_usuariopizzeriarol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('subgerente', 'Subgerente'), ('empleado', 'Empleado'), ('dueno', 'Dueño'), ('cajero', 'Cajero'), ('solo_lectura', 'Solo lectura'), ('sin_rol', 'Sin Rol')], default='empleado', max_length=30),
        ),
        migrations.CreateModel(
            name='TokenNumericoAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=128)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_autorizacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
