# Generated by Django 5.2.1 on 2025-08-04 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_tokennumericoplano_delete_tokennumericoautorizacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokennumericoplano',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='usuariopizzeriarol',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usuariopizzeriarol',
            name='pizzeria',
        ),
        migrations.RemoveField(
            model_name='usuariopizzeriarol',
            name='user',
        ),
        migrations.DeleteModel(
            name='DuenoPizzeria',
        ),
        migrations.DeleteModel(
            name='TokenNumericoPlano',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UsuarioPizzeriaRol',
        ),
    ]
