# Generated by Django 5.2.1 on 2025-08-10 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenNumericoPlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=6)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin_plano', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('subgerente', 'Subgerente'), ('empleado', 'Empleado'), ('dueno', 'Dueño'), ('cajero', 'Cajero'), ('solo_lectura', 'Solo lectura'), ('sin_rol', 'Sin Rol')], default='empleado', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DuenoPizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dueno', models.ForeignKey(db_column='dueno_id', on_delete=django.db.models.deletion.CASCADE, related_name='pizzeria_asignaciones', to=settings.AUTH_USER_MODEL)),
                ('pizzeria', models.ForeignKey(db_column='pizzeria_id', on_delete=django.db.models.deletion.CASCADE, related_name='dueno_asignaciones', to='ventas.pizzeria')),
            ],
            options={
                'verbose_name': 'Asignación Dueño-Pizzería',
                'verbose_name_plural': 'Asignaciones Dueño-Pizzería',
                'db_table': 'dueno_pizzeria',
                'unique_together': {('dueno', 'pizzeria')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioPizzeriaRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('dueno', 'Dueño'), ('gerente', 'Gerente'), ('subgerente', 'Subgerente'), ('cajero', 'Cajero'), ('empleado', 'Empleado')], max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pizzeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_con_rol', to='ventas.pizzeria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles_por_pizzeria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol de usuario en pizzería',
                'verbose_name_plural': 'Roles de usuarios en pizzerías',
                'db_table': 'usuario_pizzeria_rol',
                'unique_together': {('user', 'pizzeria')},
            },
        ),
    ]
