# Generated by Django 5.2.1 on 2025-08-29 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pizzerias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.PositiveBigIntegerField(blank=True, help_text='Id_Pro del catálogo base de Martin', null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(help_text='Categoría del producto (ej. Pizza, Bebida, Postre)', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto (opcional)', null=True)),
                ('activo', models.BooleanField(default=True, help_text='¿Está disponible para la venta?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pizzeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='pizzerias.pizzeria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('pizzeria', 'id_externo'), name='uniq_producto_idexterno_por_pizzeria')],
            },
        ),
    ]
