# Generated by Django 5.2.1 on 2025-08-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('categoria', models.CharField(help_text='Categoría del producto (ej. Pizza, Bebida, Postre)', max_length=50)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del producto (opcional)', null=True)),
                ('activo', models.BooleanField(default=True, help_text='¿Está disponible para la venta?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['nombre'],
            },
        ),
    ]
