# Generated by Django 5.2.1 on 2025-08-10 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='pizzeria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ventas.pizzeria'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('pizzeria', 'id_externo'), name='uniq_producto_idexterno_por_pizzeria'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('pizzeria', 'nombre'), name='uniq_producto_nombre_por_pizzeria'),
        ),
    ]
