# Generated by Django 5.2.1 on 2025-08-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_externo',
            field=models.PositiveBigIntegerField(blank=True, help_text='Id_Pro del catálogo base de Martin', null=True),
        ),
    ]
