# Generated by Django 5.2.1 on 2025-08-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('pizzeria', 'nombre')},
        ),
    ]
