# Generated by Django 5.2.1 on 2025-08-10 04:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_unique_together'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), models.F('pizzeria'), name='uniq_producto_nombre_pizzeria_ci'),
        ),
    ]
