# Generated by Django 5.2.1 on 2025-08-29 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_producto_id_externo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producto',
            name='uniq_producto_nombre_por_pizzeria',
        ),
    ]
